<?php

namespace App\Services;

use App\Models\User;

class PermissionService
{
    public function can(User $user, string $permission): bool
    {
        $rolePermissions = config("erp.roles.{$user->role}", []);

        if (in_array('*', $rolePermissions, true)) {
            return true;
        }

        foreach ($rolePermissions as $allowed) {
            if ($allowed === $permission) {
                return true;
            }

            if (str_ends_with($allowed, '.*')) {
                $prefix = rtrim($allowed, '.*');
                if ($permission === $prefix || str_starts_with($permission, $prefix.'.')) {
                    return true;
                }
            }
        }

        return false;
    }

    public function canRoute(User $user, ?string $routeName): bool
    {
        if (! $routeName) {
            return true;
        }

        $permission = $this->permissionFromRoute($routeName);

        return $this->can($user, $permission);
    }

    public function permissionFromRoute(string $routeName): string
    {
        $map = [
            'dashboard' => 'dashboard',
            'parts.index' => 'parts',
            'parts.store' => 'parts',
            'parts.update' => 'parts',
            'parts.destroy' => 'parts',
            'parts.import' => 'parts.import',
            'parts.import.store' => 'parts.import',
            'stock.index' => 'stock',
            'stock.movements' => 'stock',
            'stock.adjustment' => 'stock',
            'stock.adjustment.store' => 'stock',
            'quotations.index' => 'quotations',
            'quotations.create' => 'quotations',
            'quotations.store' => 'quotations',
            'quotations.show' => 'quotations',
            'quotations.convert' => 'quotations',
            'sales-invoices.index' => 'sales',
            'sales-invoices.create' => 'sales',
            'sales-invoices.store' => 'sales',
            'sales-invoices.post' => 'sales',
            'sale-returns.index' => 'sale-returns',
            'sale-returns.create' => 'sale-returns',
            'sale-returns.store' => 'sale-returns',
            'sale-returns.post' => 'sale-returns',
            'purchase-returns.index' => 'purchase-returns',
            'purchase-returns.create' => 'purchase-returns',
            'purchase-returns.store' => 'purchase-returns',
            'purchase-returns.post' => 'purchase-returns',
            'payments.index' => 'payments',
            'payments.create' => 'payments',
            'payments.store' => 'payments',
            'customers.statement' => 'payments',
            'vendors.statement' => 'payments',
            'stock-counts.index' => 'stock-counts',
            'stock-counts.create' => 'stock-counts',
            'stock-counts.store' => 'stock-counts',
            'stock-counts.show' => 'stock-counts',
            'stock-counts.post' => 'stock-counts',
            'parts.kits' => 'parts',
            'parts.kits.store' => 'parts',
            'parts.kits.destroy' => 'parts',
            'parts.alternatives.store' => 'parts',
            'parts.alternatives.destroy' => 'parts',
            'sales-invoices.void' => 'sales',
            'purchase-invoices.void' => 'purchase-invoices',
            'stock-transfers.index' => 'stock-transfers',
            'stock-transfers.create' => 'stock-transfers',
            'stock-transfers.store' => 'stock-transfers',
            'stock-transfers.complete' => 'stock-transfers',
            'purchase-orders.index' => 'purchase-orders',
            'purchase-orders.create' => 'purchase-orders',
            'purchase-orders.store' => 'purchase-orders',
            'purchase-orders.show' => 'purchase-orders',
            'purchase-orders.receive' => 'purchase-orders',
            'purchase-invoices.index' => 'purchase-invoices',
            'purchase-invoices.create' => 'purchase-invoices',
            'purchase-invoices.store' => 'purchase-invoices',
            'purchase-invoices.post' => 'purchase-invoices',
            'customers.index' => 'customers',
            'customers.store' => 'customers',
            'customers.update' => 'customers',
            'customers.destroy' => 'customers',
            'vendors.index' => 'vendors',
            'vendors.store' => 'vendors',
            'vendors.update' => 'vendors',
            'vendors.destroy' => 'vendors',
            'branches.index' => 'branches',
            'branches.store' => 'branches',
            'branches.update' => 'branches',
            'branches.destroy' => 'branches',
            'locations.index' => 'locations',
            'locations.store' => 'locations',
            'locations.update' => 'locations',
            'locations.destroy' => 'locations',
            'brands.index' => 'brands',
            'brands.store' => 'brands',
            'brands.update' => 'brands',
            'brands.destroy' => 'brands',
            'origins.index' => 'origins',
            'origins.store' => 'origins',
            'origins.update' => 'origins',
            'origins.destroy' => 'origins',
            'franchises.index' => 'franchises',
            'franchises.store' => 'franchises',
            'franchises.update' => 'franchises',
            'franchises.destroy' => 'franchises',
            'units.index' => 'units',
            'units.store' => 'units',
            'units.update' => 'units',
            'units.destroy' => 'units',
            'cheques.index' => 'cheques',
            'cheques.create' => 'cheques',
            'cheques.store' => 'cheques',
            'cheques.update' => 'cheques',
            'delivery-notes.index' => 'delivery-notes',
            'delivery-notes.create' => 'delivery-notes',
            'delivery-notes.store' => 'delivery-notes',
            'delivery-notes.show' => 'delivery-notes',
            'vehicle-orders.index' => 'vehicle-orders',
            'vehicle-orders.store' => 'vehicle-orders',
            'vehicle-orders.update' => 'vehicle-orders',
            'vehicle-orders.destroy' => 'vehicle-orders',
            'vehicles.expenses' => 'workshop',
            'vehicles.expenses.store' => 'workshop',
            'vehicle-expenses.destroy' => 'workshop',
            'locale.switch' => 'dashboard',
            'settings.index' => 'settings',
            'settings.update' => 'settings',
            'discount-rules.store' => 'settings',
            'discount-rules.destroy' => 'settings',
            'users.index' => 'users',
            'users.update' => 'users',
            'pricing.resolve' => 'sales',
            'documents.sales-invoice.pdf' => 'sales',
            'documents.purchase-invoice.pdf' => 'purchase-invoices',
            'documents.delivery-note.pdf' => 'delivery-notes',
            'documents.quotation.pdf' => 'quotations',
            'documents.purchase-order.pdf' => 'purchase-orders',
            'documents.payment-receipt.pdf' => 'payments',
            'documents.payslip.pdf' => 'hr',
            'documents.part.label' => 'parts',
            'documents.part.barcode' => 'parts',
            'accounts.index' => 'finance',
            'accounts.store' => 'finance',
            'accounts.update' => 'finance',
            'accounts.destroy' => 'finance',
            'journal-entries.index' => 'finance',
            'journal-entries.create' => 'finance',
            'journal-entries.store' => 'finance',
            'journal-entries.show' => 'finance',
            'finance.periods.index' => 'finance',
            'finance.periods.close' => 'finance',
            'finance.periods.reopen' => 'finance',
            'finance.reports.index' => 'finance',
            'finance.reports.trial-balance' => 'finance',
            'finance.reports.income-statement' => 'finance',
            'finance.reports.balance-sheet' => 'finance',
            'finance.reports.customer-aging' => 'finance',
            'finance.reports.vendor-aging' => 'finance',
            'vehicles.index' => 'workshop',
            'vehicles.store' => 'workshop',
            'vehicles.update' => 'workshop',
            'vehicles.destroy' => 'workshop',
            'job-cards.index' => 'workshop',
            'job-cards.create' => 'workshop',
            'job-cards.store' => 'workshop',
            'job-cards.show' => 'workshop',
            'job-cards.update-status' => 'workshop',
            'job-cards.convert' => 'workshop',
            'workshop.reports.wip' => 'workshop',
            'departments.index' => 'hr',
            'departments.store' => 'hr',
            'departments.update' => 'hr',
            'departments.destroy' => 'hr',
            'employees.index' => 'hr',
            'employees.show' => 'hr',
            'employees.store' => 'hr',
            'employees.update' => 'hr',
            'employees.destroy' => 'hr',
            'attendance.index' => 'hr',
            'attendance.store' => 'hr',
            'payroll.index' => 'hr',
            'payroll.create' => 'hr',
            'payroll.store' => 'hr',
            'payroll.show' => 'hr',
            'payroll.post' => 'hr',
            'payroll.pay' => 'hr',
            'payroll.update-item' => 'hr',
            'payroll.regenerate' => 'hr',
            'public-holidays.index' => 'hr',
            'public-holidays.store' => 'hr',
            'public-holidays.update' => 'hr',
            'public-holidays.destroy' => 'hr',
            'leave.index' => 'hr',
            'leave.create' => 'hr',
            'leave.store' => 'hr',
            'leave.approve' => 'hr',
            'leave.reject' => 'hr',
            'hr.reports.expiring-documents' => 'hr',
            'reports.index' => 'reports',
            'reports.show' => 'reports',
            'reports.pdf' => 'reports',
            'reports.csv' => 'reports',
            'sales-invoices.edit-posted' => 'sales',
            'sales-invoices.update-posted' => 'sales',
            'purchase-invoices.edit-posted' => 'purchase-invoices',
            'purchase-invoices.update-posted' => 'purchase-invoices',
            'users.permissions.update' => 'users',
            'currencies.index' => 'currencies',
            'currencies.store' => 'currencies',
            'currencies.update' => 'currencies',
            'currencies.destroy' => 'currencies',
            'currencies.set-rate' => 'currencies',
            'proforma-invoices.index' => 'proforma',
            'proforma-invoices.create' => 'proforma',
            'proforma-invoices.store' => 'proforma',
            'proforma-invoices.show' => 'proforma',
            'proforma-invoices.convert' => 'proforma',
            'pos.index' => 'pos',
            'pos.open-session' => 'pos',
            'pos.counter' => 'pos',
            'pos.search-parts' => 'pos',
            'pos.session-report' => 'pos',
            'pos.quick-sale' => 'pos',
            'pos.close-session' => 'pos',
            'pick-tickets.index' => 'pick-tickets',
            'pick-tickets.create-from-invoice' => 'pick-tickets',
            'pick-tickets.show' => 'pick-tickets',
            'pick-tickets.confirm' => 'pick-tickets',
            'cash-book.index' => 'cash-book',
            'cash-book.create' => 'cash-book',
            'cash-book.store' => 'cash-book',
            'fixed-assets.index' => 'fixed-assets',
            'fixed-assets.create' => 'fixed-assets',
            'fixed-assets.store' => 'fixed-assets',
            'fixed-assets.show' => 'fixed-assets',
            'fixed-assets.depreciate' => 'fixed-assets',
            'fixed-asset-categories.index' => 'fixed-assets',
            'fixed-asset-categories.store' => 'fixed-assets',
            'fixed-asset-categories.update' => 'fixed-assets',
            'fixed-asset-categories.destroy' => 'fixed-assets',
            'stock-batches.index' => 'stock-batches',
            'audit-logs.index' => 'audit-logs',
            'showroom-vehicles.index' => 'showroom-vehicles',
            'showroom-vehicles.create' => 'showroom-vehicles',
            'showroom-vehicles.store' => 'showroom-vehicles',
            'showroom-vehicles.show' => 'showroom-vehicles',
            'showroom-vehicles.transfer' => 'showroom-vehicles',
            'showroom-vehicles.sell' => 'showroom-vehicles',
            'showroom-transfers.receive' => 'showroom-vehicles',
            'transport-drivers.index' => 'transport',
            'transport-drivers.store' => 'transport',
            'transport-drivers.update' => 'transport',
            'transport-drivers.destroy' => 'transport',
            'transport.shipments.index' => 'transport',
            'transport.shipments.create' => 'transport',
            'transport.shipments.store' => 'transport',
            'transport.shipments.show' => 'transport',
            'transport.shipments.update-status' => 'transport',
            'transport.shipments.from-delivery-note' => 'transport',
            'transport.cash-vouchers.index' => 'transport',
            'transport.cash-vouchers.create' => 'transport',
            'transport.cash-vouchers.store' => 'transport',
            'transport.cash-vouchers.show' => 'transport',
            'transport.cash-vouchers.post' => 'transport',
            'transport.shipping-status.index' => 'transport',
        ];

        if (isset($map[$routeName])) {
            return $map[$routeName];
        }

        return explode('.', $routeName)[0] ?? $routeName;
    }
}
