<?php

return [

    /*
    |--------------------------------------------------------------------------
    | IAAPCO InventoryHas import phases (dependency order)
    |--------------------------------------------------------------------------
    */
    'phases' => [
        'organization' => ['branches', 'departments', 'locations'],
        'masters' => ['brands', 'origins', 'franchises', 'units', 'parts', 'customers', 'vendors', 'accounts'],
        'inventory' => ['stock_balances', 'stock_movements', 'stock_transfers'],
        'sales' => ['quotations', 'sales_invoices', 'sale_returns'],
        'purchase' => ['purchase_orders', 'purchase_invoices'],
        'finance' => ['journal_entries', 'payment_receipts'],
        'workshop' => ['vehicles', 'job_cards'],
        'hr' => ['employees'],
    ],

    'entities' => [

        'branches' => [
            'target' => 'branches',
            'legacy_tables' => ['Branch', 'Branches', 'Store', 'Stores'],
            'legacy_key' => ['BranchID', 'StoreID', 'ID', 'Code'],
            'map' => [
                'code' => ['BranchCode', 'Code', 'StoreID', 'ID'],
                'name' => ['BranchName', 'Name', 'StoreDesc', 'Description'],
                'name_ar' => ['BranchNameAr', 'NameAr', 'Name_Arb'],
                'phone' => ['Phone', 'Tel'],
                'address' => ['Address', 'Addr'],
            ],
        ],

        'departments' => [
            'target' => 'departments',
            'legacy_tables' => ['Department', 'Departments'],
            'legacy_key' => ['DeptID', 'DepartmentID', 'ID', 'Code'],
            'map' => [
                'code' => ['DeptCode', 'Code', 'DepartmentCode'],
                'name' => ['DeptName', 'Name', 'DepartmentName'],
                'name_ar' => ['DeptNameAr', 'NameAr'],
            ],
        ],

        'locations' => [
            'target' => 'locations',
            'legacy_tables' => ['Location', 'Locations', 'BinLocation'],
            'legacy_key' => ['LocationID', 'LocID', 'ID', 'Code'],
            'map' => [
                'branch' => ['BranchID', 'StoreID', 'BranchCode'],
                'code' => ['LocationCode', 'LocCode', 'Code', 'BinCode'],
                'name' => ['LocationName', 'LocName', 'Name', 'Description'],
                'aisle' => ['Aisle'],
                'rack' => ['Rack'],
                'bin' => ['Bin', 'BinLocation'],
            ],
        ],

        'brands' => [
            'target' => 'brands',
            'legacy_tables' => ['Brand', 'Brands', 'ItemBrand'],
            'legacy_key' => ['BrandID', 'ID', 'Code'],
            'map' => [
                'code' => ['BrandCode', 'Code'],
                'name' => ['BrandName', 'Name', 'Description'],
                'name_ar' => ['BrandNameAr', 'NameAr'],
            ],
        ],

        'origins' => [
            'target' => 'origins',
            'legacy_tables' => ['Origin', 'Origins', 'Country'],
            'legacy_key' => ['OriginID', 'CountryID', 'ID', 'Code'],
            'map' => [
                'code' => ['OriginCode', 'CountryCode', 'Code'],
                'name' => ['OriginName', 'CountryName', 'Name'],
            ],
        ],

        'franchises' => [
            'target' => 'franchises',
            'legacy_tables' => ['Franchise', 'Franchises'],
            'legacy_key' => ['FrID', 'FranchiseID', 'ID', 'Code'],
            'map' => [
                'code' => ['FrCode', 'Code'],
                'name' => ['FrName', 'Name', 'FranchiseName'],
            ],
        ],

        'units' => [
            'target' => 'units',
            'legacy_tables' => ['Unit', 'Units'],
            'legacy_key' => ['UnitID', 'ID', 'Code'],
            'map' => [
                'code' => ['UnitCode', 'Code'],
                'name' => ['UnitName', 'Name', 'Description'],
            ],
        ],

        'parts' => [
            'target' => 'parts',
            'legacy_tables' => ['Item', 'Items', 'Part', 'Parts'],
            'legacy_key' => ['ItemCode', 'PartNo', 'PartNumber', 'Code'],
            'map' => [
                'part_number' => ['ItemCode', 'PartNo', 'PartNumber', 'Code'],
                'oem_no' => ['OEMNo', 'OEM', 'OemNo'],
                'manufacturer_part_no' => ['MfrCode', 'ManufacturerPartNo', 'MfrPartNo'],
                'barcode' => ['Barcode', 'BarCode'],
                'brand' => ['BrandID', 'BrandCode'],
                'origin' => ['OriginID', 'CountryID'],
                'franchise' => ['FrID', 'FranchiseID'],
                'description_en' => ['Description', 'Desc', 'ItemDesc', 'Name'],
                'description_ar' => ['DescriptionAr', 'DescAr', 'ItemDescAr'],
                'list_price' => ['SalePrice', 'ListPrice', 'Price1', 'RetailPrice'],
                'price_2' => ['Price2', 'WholesalePrice'],
                'price_3' => ['Price3', 'CorporatePrice'],
                'cost_price' => ['AveCost', 'CostPrice', 'Cost', 'AvgCost'],
                'min_stock' => ['MinQty', 'MinStock', 'ReorderLevel'],
                'max_stock' => ['MaxQty', 'MaxStock'],
                'hs_code' => ['HSCode', 'HsCode'],
                'weight' => ['Weight'],
                'active' => ['Active', 'IsActive', 'Status'],
            ],
            'stock_qty_columns' => [
                ['qty' => ['Qty1', 'Qty_1'], 'location' => ['Location1', 'Location', 'Loc1']],
                ['qty' => ['Qty2'], 'location' => ['Location2', 'Loc2']],
                ['qty' => ['Qty3'], 'location' => ['Location3', 'Loc3']],
                ['qty' => ['Qty4'], 'location' => ['Location4', 'Loc4']],
                ['qty' => ['Qty5'], 'location' => ['Location5', 'Loc5']],
                ['qty' => ['Qty6'], 'location' => ['Location6', 'Loc6']],
                ['qty' => ['Qty7'], 'location' => ['Location7', 'Loc7']],
                ['qty' => ['Qty8'], 'location' => ['Location8', 'Loc8']],
            ],
            'stock_branch' => ['StoreID', 'BranchID', 'BranchCode'],
            'stock_single_qty' => ['Qty', 'OnHandQty', 'StockQty', 'BalanceQty'],
        ],

        'customers' => [
            'target' => 'customers',
            'legacy_tables' => ['Customer', 'Customers'],
            'legacy_key' => ['CustCode', 'CustomerCode', 'Code', 'ID'],
            'map' => [
                'code' => ['CustCode', 'CustomerCode', 'Code'],
                'branch' => ['BranchID', 'StoreID'],
                'name' => ['CustName', 'CustomerName', 'Name'],
                'name_ar' => ['CustNameAr', 'NameAr'],
                'contact_person' => ['ContactPerson', 'Contact'],
                'phone' => ['Phone', 'Tel'],
                'mobile' => ['Mobile', 'Cell'],
                'email' => ['Email'],
                'address' => ['Address', 'Addr'],
                'city' => ['City'],
                'country' => ['Country'],
                'vat_no' => ['VATNo', 'VatNo', 'TaxNo'],
                'customer_type' => ['CustType', 'CustomerType', 'Type'],
                'credit_limit' => ['CreditLimit', 'Credit'],
                'balance' => ['Balance', 'CurrentBalance'],
                'payment_terms' => ['PaymentTerms', 'TermsDays'],
            ],
        ],

        'vendors' => [
            'target' => 'vendors',
            'legacy_tables' => ['Vendor', 'Vendors', 'Supplier', 'Suppliers'],
            'legacy_key' => ['VendCode', 'VendorCode', 'Code', 'ID'],
            'map' => [
                'code' => ['VendCode', 'VendorCode', 'SupplierCode', 'Code'],
                'name' => ['VendName', 'VendorName', 'SupplierName', 'Name'],
                'name_ar' => ['VendNameAr', 'NameAr'],
                'phone' => ['Phone', 'Tel'],
                'email' => ['Email'],
                'address' => ['Address'],
                'vat_no' => ['VATNo', 'VatNo'],
                'balance' => ['Balance'],
            ],
        ],

        'accounts' => [
            'target' => 'accounts',
            'legacy_tables' => ['Account', 'Accounts', 'ChartOfAccount'],
            'legacy_key' => ['AccCode', 'AccountCode', 'Code', 'ID'],
            'map' => [
                'account_code' => ['AccCode', 'AccountCode', 'Code'],
                'name' => ['AcNameEng', 'AccountName', 'Name', 'Description'],
                'name_ar' => ['AcNameArb', 'NameAr'],
                'account_type' => ['AccType', 'AccountType', 'Type'],
                'opening_balance' => ['OpenBalance', 'OpeningBalance'],
                'current_balance' => ['Balance', 'CurrentBalance'],
            ],
        ],

        'stock_movements' => [
            'target' => 'stock_movements',
            'legacy_tables' => ['ItemMove', 'ItemMoves', 'StockMove', 'MoveRep'],
            'legacy_key' => ['MoveID', 'ID', 'TransID'],
            'header_key' => null,
            'map' => [
                'branch' => ['BranchID', 'StoreID'],
                'part' => ['ItemCode', 'PartNo'],
                'location' => ['LocationID', 'LocCode', 'Location'],
                'movement_type' => ['MoveType', 'TransType', 'Type'],
                'reference_no' => ['RefNo', 'ReferenceNo', 'InvNo'],
                'quantity_in' => ['QtyIn', 'InQty'],
                'quantity_out' => ['QtyOut', 'OutQty'],
                'unit_cost' => ['UnitCost', 'Cost'],
                'movement_date' => ['MoveDate', 'TransDate', 'Date'],
                'remarks' => ['Remarks', 'Notes'],
            ],
        ],

        'stock_transfers' => [
            'target' => 'stock_transfers',
            'legacy_tables' => ['TransferHeader', 'TransferHead'],
            'legacy_key' => ['TransferID', 'TransID', 'ID', 'TransferNo'],
            'detail_table' => ['TransferDetail', 'TransferDet'],
            'detail_fk' => ['TransferID', 'TransID', 'HeaderID'],
            'map' => [
                'transfer_no' => ['TransferNo', 'TransNo', 'RefNo'],
                'from_branch' => ['FromBranchID', 'FromStoreID'],
                'to_branch' => ['ToBranchID', 'ToStoreID'],
                'transfer_date' => ['TransferDate', 'TransDate', 'Date'],
                'status' => ['Status', 'Posted'],
                'remarks' => ['Remarks', 'Notes'],
            ],
            'detail_map' => [
                'part' => ['ItemCode', 'PartNo'],
                'from_location' => ['FromLocID', 'FromLocation'],
                'to_location' => ['ToLocID', 'ToLocation'],
                'quantity' => ['Qty', 'Quantity'],
                'unit_cost' => ['UnitCost', 'Cost'],
            ],
        ],

        'quotations' => [
            'target' => 'quotations',
            'legacy_tables' => ['PickHeader'],
            'legacy_key' => ['PickID', 'ID', 'PickNo'],
            'detail_table' => ['PickDetail'],
            'detail_fk' => ['PickID', 'HeaderID'],
            'filter' => ['Qtype' => ['Q', 'QUOT', 'QUOTATION', '1']],
            'map' => [
                'quotation_no' => ['PickNo', 'QNo', 'RefNo'],
                'branch' => ['BranchID', 'StoreID'],
                'customer' => ['CustCode', 'CustomerCode'],
                'quotation_date' => ['PickDate', 'InvDate', 'Date'],
                'valid_until' => ['ValidUntil', 'ExpiryDate'],
                'status' => ['Status', 'Posted'],
                'subtotal' => ['SubTotal', 'Amount'],
                'vat_amount' => ['VATAmount', 'TaxAmount'],
                'total_amount' => ['TotalAmount', 'NetAmount', 'Amount'],
                'remarks' => ['Remarks', 'Notes'],
            ],
            'detail_map' => [
                'part' => ['ItemCode', 'PartNo'],
                'quantity' => ['Qty', 'Quantity', 'PickQty'],
                'unit_price' => ['UnitPrice', 'Price', 'SalePrice'],
                'discount_percent' => ['DiscPercent', 'Discount'],
                'vat_percent' => ['VATPercent', 'TaxRate'],
                'line_total' => ['LineTotal', 'Amount'],
            ],
        ],

        'sales_invoices' => [
            'target' => 'sales_invoices',
            'legacy_tables' => ['SalesHeader', 'SalesHead', 'PickHeader'],
            'legacy_key' => ['SalesID', 'PickID', 'ID', 'SInvNo'],
            'detail_table' => ['SalesDetail', 'SalesDet', 'PickDetail'],
            'detail_fk' => ['SalesID', 'PickID', 'HeaderID', 'SInvNo'],
            'filter' => ['Qtype' => ['S', 'SALE', 'INV', '2']],
            'map' => [
                'invoice_no' => ['SInvNo', 'InvoiceNo', 'InvNo', 'PickNo'],
                'branch' => ['BranchID', 'StoreID'],
                'customer' => ['CustCode', 'CustomerCode'],
                'invoice_date' => ['InvDate', 'SalesDate', 'PickDate', 'Date'],
                'invoice_type' => ['InvType', 'SalesType', 'PaymentType'],
                'status' => ['Posted', 'Status', 'SSPosted'],
                'subtotal' => ['SubTotal', 'Amount'],
                'discount_amount' => ['DiscAmount', 'Discount'],
                'vat_amount' => ['VATAmount', 'TaxAmount'],
                'total_amount' => ['TotalAmount', 'NetAmount', 'Amount'],
                'paid_amount' => ['PaidAmount', 'Paid'],
                'remarks' => ['Remarks', 'Notes'],
            ],
            'detail_map' => [
                'part' => ['ItemCode', 'PartNo'],
                'location' => ['LocationID', 'LocCode', 'Location'],
                'quantity' => ['Qty', 'SalesQty', 'InvQty'],
                'unit_price' => ['UnitPrice', 'Price'],
                'unit_cost' => ['UnitCost', 'AveCost', 'Cost'],
                'discount_percent' => ['DiscPercent'],
                'vat_percent' => ['VATPercent', 'TaxRate'],
                'line_total' => ['LineTotal', 'Amount'],
            ],
        ],

        'sale_returns' => [
            'target' => 'sale_returns',
            'legacy_tables' => ['RtnSalesHeader', 'RtnSalesHead'],
            'legacy_key' => ['RtnID', 'ID', 'RtnInvNo'],
            'detail_table' => ['RtnSalesDetail', 'RtnSalesDet'],
            'detail_fk' => ['RtnID', 'HeaderID'],
            'map' => [
                'return_no' => ['RtnInvNo', 'ReturnNo', 'RefNo'],
                'sales_invoice' => ['SInvNo', 'InvoiceNo', 'OriginalInvNo'],
                'branch' => ['BranchID', 'StoreID'],
                'customer' => ['CustCode'],
                'return_date' => ['RtnDate', 'InvDate', 'Date'],
                'status' => ['Posted', 'Status'],
                'total_amount' => ['TotalAmount', 'NetAmount'],
                'remarks' => ['Remarks'],
            ],
            'detail_map' => [
                'part' => ['ItemCode', 'PartNo'],
                'location' => ['LocationID', 'LocCode'],
                'quantity' => ['RtnQty', 'Qty'],
                'unit_price' => ['UnitPrice', 'Price'],
                'line_total' => ['LineTotal', 'Amount'],
            ],
        ],

        'purchase_orders' => [
            'target' => 'purchase_orders',
            'legacy_tables' => ['POHeader', 'POHead'],
            'legacy_key' => ['POID', 'ID', 'PONo'],
            'detail_table' => ['PODetail', 'PODet'],
            'detail_fk' => ['POID', 'HeaderID'],
            'map' => [
                'po_no' => ['PONo', 'OrderNo', 'RefNo'],
                'branch' => ['BranchID', 'StoreID'],
                'vendor' => ['VendCode', 'VendorCode'],
                'po_date' => ['PODate', 'OrderDate', 'Date'],
                'expected_date' => ['ExpectedDate', 'DueDate'],
                'status' => ['Status', 'Posted'],
                'subtotal' => ['SubTotal', 'Amount'],
                'vat_amount' => ['VATAmount'],
                'total_amount' => ['TotalAmount', 'NetAmount'],
                'remarks' => ['Remarks'],
            ],
            'detail_map' => [
                'part' => ['ItemCode', 'PartNo'],
                'quantity' => ['Qty', 'OrderQty'],
                'unit_price' => ['UnitPrice', 'Price'],
                'received_qty' => ['ReceivedQty', 'RecvQty'],
                'line_total' => ['LineTotal', 'Amount'],
            ],
        ],

        'purchase_invoices' => [
            'target' => 'purchase_invoices',
            'legacy_tables' => ['PurchaseHeader', 'PurchaseHead', 'RecieveHeader'],
            'legacy_key' => ['PurchaseID', 'RecvID', 'ID', 'InvNo'],
            'detail_table' => ['PurchaseDetail', 'PurchaseDet', 'RecieveDetail'],
            'detail_fk' => ['PurchaseID', 'RecvID', 'HeaderID'],
            'map' => [
                'invoice_no' => ['InvNo', 'PurchaseNo', 'RefNo'],
                'branch' => ['BranchID', 'StoreID'],
                'vendor' => ['VendCode', 'VendorCode'],
                'purchase_order' => ['PONo', 'POID'],
                'invoice_date' => ['InvDate', 'PurchaseDate', 'RecvDate'],
                'vendor_invoice_no' => ['VendorInvNo', 'SuppInvNo'],
                'status' => ['Posted', 'Status'],
                'subtotal' => ['SubTotal'],
                'vat_amount' => ['VATAmount'],
                'total_amount' => ['TotalAmount', 'NetAmount'],
                'paid_amount' => ['PaidAmount'],
                'remarks' => ['Remarks'],
            ],
            'detail_map' => [
                'part' => ['ItemCode', 'PartNo'],
                'location' => ['LocationID', 'LocCode'],
                'quantity' => ['Qty', 'RecvQty'],
                'unit_price' => ['UnitPrice', 'Cost'],
                'line_total' => ['LineTotal', 'Amount'],
            ],
        ],

        'journal_entries' => [
            'target' => 'journal_entries',
            'legacy_tables' => ['GenHeader', 'GenHead', 'JournalHeader'],
            'legacy_key' => ['GenID', 'JournalID', 'ID', 'EntryNo'],
            'detail_table' => ['GenDetail', 'GenDet', 'JournalDetail'],
            'detail_fk' => ['GenID', 'JournalID', 'HeaderID'],
            'map' => [
                'entry_no' => ['EntryNo', 'GenNo', 'RefNo', 'VoucherNo'],
                'branch' => ['BranchID', 'StoreID'],
                'entry_date' => ['EntryDate', 'GenDate', 'VoucherDate', 'Date'],
                'description' => ['Description', 'Narration', 'Remarks'],
                'status' => ['Posted', 'Status'],
            ],
            'detail_map' => [
                'account' => ['AccCode', 'AccountCode'],
                'debit' => ['Debit', 'Dr'],
                'credit' => ['Credit', 'Cr'],
                'description' => ['LineDesc', 'Description'],
            ],
        ],

        'payment_receipts' => [
            'target' => 'payment_receipts',
            'legacy_tables' => ['PayHeader', 'PayHead', 'PayEnt'],
            'legacy_key' => ['PayID', 'ID', 'ReceiptNo'],
            'detail_table' => ['PayDetail', 'PayDet'],
            'detail_fk' => ['PayID', 'HeaderID'],
            'map' => [
                'receipt_no' => ['ReceiptNo', 'PayNo', 'RefNo'],
                'party_type' => ['PartyType', 'PayType'],
                'customer' => ['CustCode'],
                'vendor' => ['VendCode'],
                'branch' => ['BranchID', 'StoreID'],
                'receipt_date' => ['PayDate', 'ReceiptDate', 'Date'],
                'payment_method' => ['PayMethod', 'PaymentMethod'],
                'amount' => ['Amount', 'PayAmount', 'NetAmount'],
                'reference_no' => ['RefNo', 'ChequeNo'],
                'sales_invoice' => ['SInvNo', 'InvoiceNo'],
                'status' => ['Posted', 'Status'],
                'remarks' => ['Remarks'],
            ],
        ],

        'vehicles' => [
            'target' => 'vehicles',
            'legacy_tables' => ['ServiceVehicle', 'Vehicle', 'Vehicles'],
            'legacy_key' => ['VehicleID', 'ID', 'PlateNo'],
            'map' => [
                'customer' => ['CustCode', 'CustomerCode'],
                'plate_no' => ['PlateNo', 'Plate', 'RegNo'],
                'make' => ['Make', 'VehicleMake'],
                'model' => ['Model', 'VehicleModel'],
                'year' => ['Year', 'ModelYear'],
                'vin' => ['VIN', 'ChassisNo'],
                'color' => ['Color'],
                'istimara_expiry' => ['IstimaraExpiry', 'RegExpiry'],
                'remarks' => ['Remarks'],
            ],
        ],

        'job_cards' => [
            'target' => 'job_cards',
            'legacy_tables' => ['WIPStatus', 'JobCard', 'ServiceJob'],
            'legacy_key' => ['WIPID', 'JobID', 'ID', 'JobNo'],
            'map' => [
                'job_no' => ['JobNo', 'WIPNo', 'RefNo'],
                'branch' => ['BranchID', 'StoreID'],
                'customer' => ['CustCode'],
                'vehicle' => ['VehicleID', 'PlateNo'],
                'job_date' => ['JobDate', 'OpenDate', 'Date'],
                'promised_date' => ['PromisedDate', 'DueDate'],
                'status' => ['Status', 'WIPStatus'],
                'labor_total' => ['LaborTotal', 'LabourAmount'],
                'parts_total' => ['PartsTotal', 'PartsAmount'],
                'total_amount' => ['TotalAmount', 'NetAmount'],
                'mechanic' => ['MechanicID', 'EmployeeID'],
                'complaint' => ['Complaint', 'Problem'],
                'remarks' => ['Remarks'],
            ],
        ],

        'employees' => [
            'target' => 'employees',
            'legacy_tables' => ['Employee', 'Employees', 'EmpMaster'],
            'legacy_key' => ['EmpID', 'EmployeeID', 'ID', 'EmployeeNo'],
            'map' => [
                'employee_no' => ['EmployeeNo', 'EmpNo', 'Code'],
                'branch' => ['BranchID', 'StoreID'],
                'department' => ['DeptID', 'DepartmentID'],
                'name' => ['EmpName', 'Name', 'EmployeeName'],
                'name_ar' => ['EmpNameAr', 'NameAr'],
                'phone' => ['Phone', 'Mobile'],
                'email' => ['Email'],
                'hire_date' => ['HireDate', 'JoinDate'],
                'job_title' => ['JobTitle', 'Designation'],
                'basic_salary' => ['BasicSalary', 'Salary'],
                'housing_allowance' => ['HousingAllowance', 'Housing'],
                'transport_allowance' => ['TransportAllowance', 'Transport'],
                'aqama_no' => ['AqamaNo', 'IqamaNo'],
                'aqama_expiry' => ['AqamaExpiry', 'IqamaExpiry'],
                'license_no' => ['LicenseNo'],
                'license_expiry' => ['LicenseExpiry'],
            ],
        ],

    ],

    'defaults' => [
        'brand_code' => 'LEG',
        'brand_name' => 'Legacy Import',
        'origin_code' => 'IMP',
        'origin_name' => 'Imported',
        'franchise_code' => 'GEN',
        'franchise_name' => 'General',
        'unit_code' => 'EA',
        'unit_name' => 'Each',
        'branch_code' => 'HO',
        'branch_name' => 'Head Office',
        'location_code' => 'MAIN',
        'location_name' => 'Main Warehouse',
    ],

    'default_connection' => env('LEGACY_IMPORT_CONNECTION', 'legacy_sqlsrv'),

];
