<?php

return [

    'categories' => [
        'sales' => ['label' => 'Sales', 'label_ar' => 'المبيعات'],
        'inventory' => ['label' => 'Inventory', 'label_ar' => 'المخزون'],
        'purchase' => ['label' => 'Purchase', 'label_ar' => 'المشتريات'],
        'finance' => ['label' => 'Finance', 'label_ar' => 'المالية'],
        'workshop' => ['label' => 'Workshop', 'label_ar' => 'الورشة'],
        'hr' => ['label' => 'HR', 'label_ar' => 'الموارد البشرية'],
        'masters' => ['label' => 'Master Lists', 'label_ar' => 'القوائم الرئيسية'],
        'transport' => ['label' => 'Transport', 'label_ar' => 'النقل'],
    ],

    'reports' => [
        'customer-list' => [
            'legacy' => 'CustomerList',
            'category' => 'masters',
            'title' => 'Customer List',
            'title_ar' => 'قائمة العملاء',
            'permission' => 'reports',
            'filters' => [],
        ],
        'vendor-list' => [
            'legacy' => 'VendorList',
            'category' => 'masters',
            'title' => 'Vendor List',
            'title_ar' => 'قائمة الموردين',
            'permission' => 'reports',
            'filters' => [],
        ],
        'parts-master' => [
            'legacy' => 'PartNoArb',
            'category' => 'masters',
            'title' => 'Parts Master List',
            'title_ar' => 'قائمة قطع الغيار',
            'permission' => 'reports',
            'filters' => ['search'],
        ],
        'sale-summary' => [
            'legacy' => 'SaleSummary',
            'category' => 'sales',
            'title' => 'Sales Summary',
            'title_ar' => 'ملخص المبيعات',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'sales-by-customer' => [
            'legacy' => 'CustRep',
            'category' => 'sales',
            'title' => 'Sales by Customer',
            'title_ar' => 'المبيعات حسب العميل',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'monthly-sales-branch' => [
            'legacy' => 'MonSalBrn',
            'category' => 'sales',
            'title' => 'Monthly Sales by Branch',
            'title_ar' => 'المبيعات الشهرية حسب الفرع',
            'permission' => 'reports',
            'filters' => ['from', 'to'],
        ],
        'daily-transactions' => [
            'legacy' => 'DailyTrans',
            'category' => 'sales',
            'title' => 'Daily Transactions',
            'title_ar' => 'المعاملات اليومية',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'sales-returns' => [
            'legacy' => 'RtnSales',
            'category' => 'sales',
            'title' => 'Sales Returns',
            'title_ar' => 'مرتجعات المبيعات',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'quotations' => [
            'legacy' => 'Qoutation',
            'category' => 'sales',
            'title' => 'Quotations List',
            'title_ar' => 'قائمة عروض الأسعار',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'top-selling-parts' => [
            'legacy' => 'SaleSummary',
            'category' => 'sales',
            'title' => 'Top Selling Parts',
            'title_ar' => 'أكثر القطع مبيعاً',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'stock-listing' => [
            'legacy' => 'Stock',
            'category' => 'inventory',
            'title' => 'Stock Listing',
            'title_ar' => 'قائمة المخزون',
            'permission' => 'reports',
            'filters' => ['branch_id', 'search'],
        ],
        'stock-by-branch' => [
            'legacy' => 'BrhQty',
            'category' => 'inventory',
            'title' => 'Stock by Branch',
            'title_ar' => 'المخزون حسب الفرع',
            'permission' => 'reports',
            'filters' => ['search'],
        ],
        'stock-by-location' => [
            'legacy' => 'LocRep',
            'category' => 'inventory',
            'title' => 'Stock by Location',
            'title_ar' => 'المخزون حسب الموقع',
            'permission' => 'reports',
            'filters' => ['branch_id', 'search'],
        ],
        'stock-cardex' => [
            'legacy' => 'Cardex',
            'category' => 'inventory',
            'title' => 'Stock Cardex',
            'title_ar' => 'كاردكس المخزون',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'part_id', 'branch_id'],
        ],
        'stock-movements' => [
            'legacy' => 'DailyTrans2',
            'category' => 'inventory',
            'title' => 'Stock Movements',
            'title_ar' => 'حركات المخزون',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id', 'movement_type'],
        ],
        'low-stock' => [
            'legacy' => 'StockOrder',
            'category' => 'inventory',
            'title' => 'Low Stock Alert',
            'title_ar' => 'تنبيه المخزون المنخفض',
            'permission' => 'reports',
            'filters' => ['branch_id'],
        ],
        'dead-stock' => [
            'legacy' => 'DeadStock',
            'category' => 'inventory',
            'title' => 'Dead Stock',
            'title_ar' => 'مخزون راكد',
            'permission' => 'reports',
            'filters' => ['branch_id', 'days'],
        ],
        'purchase-summary' => [
            'legacy' => 'InvReport',
            'category' => 'purchase',
            'title' => 'Purchase Summary',
            'title_ar' => 'ملخص المشتريات',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'daily-purchases' => [
            'legacy' => 'DailyPurTrans',
            'category' => 'purchase',
            'title' => 'Daily Purchase Transactions',
            'title_ar' => 'مشتريات يومية',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'purchases-by-vendor' => [
            'legacy' => 'ForiegnPur',
            'category' => 'purchase',
            'title' => 'Purchases by Vendor',
            'title_ar' => 'المشتريات حسب المورد',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'pending-po' => [
            'legacy' => 'PendingPO',
            'category' => 'purchase',
            'title' => 'Pending Purchase Orders',
            'title_ar' => 'أوامر شراء معلقة',
            'permission' => 'reports',
            'filters' => ['branch_id'],
        ],
        'trial-balance' => [
            'legacy' => 'GLSumRep',
            'category' => 'finance',
            'title' => 'Trial Balance',
            'title_ar' => 'ميزان المراجعة',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
            'view' => 'trial_balance',
        ],
        'income-statement' => [
            'legacy' => 'Income',
            'category' => 'finance',
            'title' => 'Income Statement',
            'title_ar' => 'قائمة الدخل',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
            'view' => 'income_statement',
        ],
        'balance-sheet' => [
            'legacy' => 'BALANCESHEET',
            'category' => 'finance',
            'title' => 'Balance Sheet',
            'title_ar' => 'الميزانية العمومية',
            'permission' => 'finance',
            'filters' => ['as_of'],
            'view' => 'balance_sheet',
        ],
        'customer-aging' => [
            'legacy' => 'AgingList',
            'category' => 'finance',
            'title' => 'Customer Aging',
            'title_ar' => 'أعمار ديون العملاء',
            'permission' => 'finance',
            'filters' => [],
            'view' => 'aging',
        ],
        'vendor-aging' => [
            'legacy' => 'AgeRep',
            'category' => 'finance',
            'title' => 'Vendor Aging',
            'title_ar' => 'أعمار ديون الموردين',
            'permission' => 'finance',
            'filters' => [],
            'view' => 'aging',
        ],
        'job-cards' => [
            'legacy' => 'JobCard',
            'category' => 'workshop',
            'title' => 'Job Cards',
            'title_ar' => 'بطاقات العمل',
            'permission' => 'workshop',
            'filters' => ['from', 'to', 'branch_id', 'status'],
        ],
        'workshop-wip' => [
            'legacy' => 'WIP',
            'category' => 'workshop',
            'title' => 'Work In Progress',
            'title_ar' => 'أعمال قيد التنفيذ',
            'permission' => 'workshop',
            'filters' => ['branch_id'],
        ],
        'payroll-summary' => [
            'legacy' => 'Payroll',
            'category' => 'hr',
            'title' => 'Payroll Summary',
            'title_ar' => 'ملخص الرواتب',
            'permission' => 'hr',
            'filters' => ['from', 'to'],
        ],
        'expiring-documents' => [
            'legacy' => 'AqamaStatus',
            'category' => 'hr',
            'title' => 'Expiring Documents',
            'title_ar' => 'وثائق منتهية الصلاحية',
            'permission' => 'hr',
            'filters' => ['days'],
            'view' => 'expiring',
        ],
        'sales-by-user' => [
            'legacy' => 'SaleByUsers',
            'category' => 'sales',
            'title' => 'Sales by User',
            'title_ar' => 'المبيعات حسب المستخدم',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'stock-by-franchise' => [
            'legacy' => 'StockByFran',
            'category' => 'inventory',
            'title' => 'Stock by Franchise',
            'title_ar' => 'المخزون حسب الامتياز',
            'permission' => 'reports',
            'filters' => ['search'],
        ],
        'payables-report' => [
            'legacy' => 'PayableRpt',
            'category' => 'finance',
            'title' => 'Payables Report',
            'title_ar' => 'تقرير الدائنين',
            'permission' => 'finance',
            'filters' => ['as_of'],
        ],
        'cash-transactions' => [
            'legacy' => 'CashTrn',
            'category' => 'finance',
            'title' => 'Cash Transactions',
            'title_ar' => 'معاملات النقدية',
            'permission' => 'finance',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'wip-by-mechanic' => [
            'legacy' => 'WIPMechanic',
            'category' => 'workshop',
            'title' => 'WIP by Mechanic',
            'title_ar' => 'أعمال قيد التنفيذ حسب الفني',
            'permission' => 'workshop',
            'filters' => ['branch_id'],
        ],
        'manufacturer-codes' => [
            'legacy' => 'MfrCodeList',
            'category' => 'masters',
            'title' => 'Manufacturer Code List',
            'title_ar' => 'قائمة رموز المصنع',
            'permission' => 'reports',
            'filters' => ['search'],
        ],
        'physical-inventory' => [
            'legacy' => 'PhyInventory',
            'category' => 'inventory',
            'title' => 'Physical Inventory Count',
            'title_ar' => 'جرد المخزون الفعلي',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'purchase-returns' => [
            'legacy' => 'PurReturn',
            'category' => 'purchase',
            'title' => 'Purchase Returns',
            'title_ar' => 'مرتجعات المشتريات',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'payment-receipts' => [
            'legacy' => 'ReceiptRpt',
            'category' => 'finance',
            'title' => 'Payment Receipts',
            'title_ar' => 'إيصالات الدفع',
            'permission' => 'finance',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'customer-statement-report' => [
            'legacy' => 'CustStatement',
            'category' => 'finance',
            'title' => 'Customer Statement Summary',
            'title_ar' => 'ملخص كشف حساب العميل',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
        ],
        'vendor-statement-report' => [
            'legacy' => 'VendStatement',
            'category' => 'finance',
            'title' => 'Vendor Statement Summary',
            'title_ar' => 'ملخص كشف حساب المورد',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
        ],
        'stock-valuation' => [
            'legacy' => 'StockVal',
            'category' => 'inventory',
            'title' => 'Stock Valuation',
            'title_ar' => 'تقييم المخزون',
            'permission' => 'reports',
            'filters' => ['branch_id'],
        ],
        'sales-by-part' => [
            'legacy' => 'SaleByPart',
            'category' => 'sales',
            'title' => 'Sales by Part',
            'title_ar' => 'المبيعات حسب القطعة',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'profit-margin' => [
            'legacy' => 'ProfitMargin',
            'category' => 'sales',
            'title' => 'Profit Margin Analysis',
            'title_ar' => 'تحليل هامش الربح',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'branch-performance' => [
            'legacy' => 'BrnPerf',
            'category' => 'sales',
            'title' => 'Branch Performance',
            'title_ar' => 'أداء الفروع',
            'permission' => 'reports',
            'filters' => ['from', 'to'],
        ],
        'open-quotations' => [
            'legacy' => 'OpenQuot',
            'category' => 'sales',
            'title' => 'Open Quotations',
            'title_ar' => 'عروض أسعار مفتوحة',
            'permission' => 'reports',
            'filters' => ['branch_id'],
        ],
        'stock-transfers-report' => [
            'legacy' => 'TransferRpt',
            'category' => 'inventory',
            'title' => 'Stock Transfers',
            'title_ar' => 'تحويلات المخزون',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'journal-entries-report' => [
            'legacy' => 'JEReport',
            'category' => 'finance',
            'title' => 'Journal Entries List',
            'title_ar' => 'قائمة قيود اليومية',
            'permission' => 'finance',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'gl-detail' => [
            'legacy' => 'GLDetail',
            'category' => 'finance',
            'title' => 'GL Detail',
            'title_ar' => 'تفاصيل الأستاذ العام',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
        ],
        'invoice-register-sales' => [
            'legacy' => 'InvRegSale',
            'category' => 'sales',
            'title' => 'Sales Invoice Register',
            'title_ar' => 'سجل فواتير المبيعات',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'invoice-register-purchase' => [
            'legacy' => 'InvRegPur',
            'category' => 'purchase',
            'title' => 'Purchase Invoice Register',
            'title_ar' => 'سجل فواتير المشتريات',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'parts-without-movement' => [
            'legacy' => 'NoMovement',
            'category' => 'inventory',
            'title' => 'Parts Without Movement',
            'title_ar' => 'قطع بدون حركة',
            'permission' => 'reports',
            'filters' => ['days', 'branch_id'],
        ],
        'reserved-stock' => [
            'legacy' => 'ReservedStock',
            'category' => 'inventory',
            'title' => 'Reserved Stock',
            'title_ar' => 'المخزون المحجوز',
            'permission' => 'reports',
            'filters' => ['branch_id'],
        ],
        'cost-vs-list-price' => [
            'legacy' => 'CostVsList',
            'category' => 'inventory',
            'title' => 'Cost vs List Price',
            'title_ar' => 'التكلفة مقابل سعر القائمة',
            'permission' => 'reports',
            'filters' => ['search'],
        ],
        'parts-master-ar' => [
            'legacy' => 'PartNoArb',
            'category' => 'masters',
            'title' => 'Parts Master (Arabic)',
            'title_ar' => 'قائمة قطع الغيار بالعربية',
            'permission' => 'reports',
            'filters' => ['search'],
            'locale' => 'ar',
        ],
        'batch-stock-list' => [
            'legacy' => 'BatchStock',
            'category' => 'inventory',
            'title' => 'Batch Stock List',
            'title_ar' => 'قائمة مخزون الدفعات',
            'permission' => 'reports',
            'filters' => ['branch_id', 'part_id'],
        ],
        'fixed-asset-register' => [
            'legacy' => 'FixedAssetReg',
            'category' => 'finance',
            'title' => 'Fixed Asset Register',
            'title_ar' => 'سجل الأصول الثابتة',
            'permission' => 'finance',
            'filters' => ['branch_id'],
        ],
        'proforma-list' => [
            'legacy' => 'ProformaList',
            'category' => 'sales',
            'title' => 'Proforma Invoice List',
            'title_ar' => 'قائمة الفواتير الأولية',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'pick-ticket-list' => [
            'legacy' => 'PickTicketList',
            'category' => 'inventory',
            'title' => 'Pick Ticket List',
            'title_ar' => 'قائمة أذونات الصرف',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id', 'status'],
        ],
        'pos-sales' => [
            'legacy' => 'POSSales',
            'category' => 'sales',
            'title' => 'POS Sales',
            'title_ar' => 'مبيعات نقاط البيع',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'cash-book-register' => [
            'legacy' => 'CashBookReg',
            'category' => 'finance',
            'title' => 'Cash Book Register',
            'title_ar' => 'سجل دفتر النقدية',
            'permission' => 'finance',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'cash-flow-statement' => [
            'legacy' => 'CashFlow',
            'category' => 'finance',
            'title' => 'Cash Flow Statement',
            'title_ar' => 'قائمة التدفقات النقدية',
            'permission' => 'finance',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'audit-log-report' => [
            'legacy' => 'AuditLogRpt',
            'category' => 'masters',
            'title' => 'Audit Log Report',
            'title_ar' => 'تقرير سجل التدقيق',
            'permission' => 'audit-logs',
            'filters' => ['from', 'to'],
        ],
        'showroom-stock' => [
            'legacy' => 'ShowroomStock',
            'category' => 'inventory',
            'title' => 'Showroom Stock',
            'title_ar' => 'مخزون صالة العرض',
            'permission' => 'reports',
            'filters' => ['branch_id', 'search'],
        ],
        'workshop-stock' => [
            'legacy' => 'WorkshopStock',
            'category' => 'inventory',
            'title' => 'Workshop Stock',
            'title_ar' => 'مخزون الورشة',
            'permission' => 'reports',
            'filters' => ['branch_id', 'search'],
        ],
        'currency-list' => [
            'legacy' => 'CurrencyList',
            'category' => 'masters',
            'title' => 'Currency List',
            'title_ar' => 'قائمة العملات',
            'permission' => 'currencies',
            'filters' => [],
        ],
        'foreign-purchases' => [
            'legacy' => 'ForiegnPur',
            'category' => 'purchase',
            'title' => 'Foreign Currency Purchases',
            'title_ar' => 'مشتريات بالعملة الأجنبية',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'batch-expiry' => [
            'legacy' => 'BatchExpiry',
            'category' => 'inventory',
            'title' => 'Batch Expiry Alert',
            'title_ar' => 'تنبيه انتهاء الدفعات',
            'permission' => 'reports',
            'filters' => ['days', 'branch_id'],
        ],
        'serial-tracker' => [
            'legacy' => 'SerialTracker',
            'category' => 'inventory',
            'title' => 'Serial Number Tracker',
            'title_ar' => 'تتبع الأرقام التسلسلية',
            'permission' => 'reports',
            'filters' => ['search', 'branch_id'],
        ],
        'gl-batch-posting' => [
            'legacy' => 'GLBatchPost',
            'category' => 'finance',
            'title' => 'GL Batch Posting',
            'title_ar' => 'ترحيل دفعات الأستاذ العام',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
        ],
        'user-activity-log' => [
            'legacy' => 'UserActivity',
            'category' => 'masters',
            'title' => 'User Activity Log',
            'title_ar' => 'سجل نشاط المستخدمين',
            'permission' => 'audit-logs',
            'filters' => ['from', 'to'],
        ],
        'pos-session-summary' => [
            'legacy' => 'POSSession',
            'category' => 'sales',
            'title' => 'POS Session Summary',
            'title_ar' => 'ملخص جلسات نقاط البيع',
            'permission' => 'pos',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'fixed-asset-depreciation' => [
            'legacy' => 'FADepreciation',
            'category' => 'finance',
            'title' => 'Fixed Asset Depreciation',
            'title_ar' => 'إهلاك الأصول الثابتة',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
        ],
        'cash-book-balance' => [
            'legacy' => 'CashBookBal',
            'category' => 'finance',
            'title' => 'Cash Book Balance',
            'title_ar' => 'رصيد دفتر النقدية',
            'permission' => 'finance',
            'filters' => ['as_of', 'branch_id'],
        ],
        'pick-ticket-pending' => [
            'legacy' => 'PickPending',
            'category' => 'inventory',
            'title' => 'Pending Pick Tickets',
            'title_ar' => 'أذونات صرف معلقة',
            'permission' => 'reports',
            'filters' => ['branch_id'],
        ],
        'proforma-open' => [
            'legacy' => 'ProformaOpen',
            'category' => 'sales',
            'title' => 'Open Proforma Invoices',
            'title_ar' => 'فواتير أولية مفتوحة',
            'permission' => 'proforma',
            'filters' => ['branch_id'],
        ],
        'currency-rate-history' => [
            'legacy' => 'CurrRateHist',
            'category' => 'masters',
            'title' => 'Currency Rate History',
            'title_ar' => 'سجل أسعار العملات',
            'permission' => 'currencies',
            'filters' => ['from', 'to'],
        ],
        'batch-valuation' => [
            'legacy' => 'BatchValuation',
            'category' => 'inventory',
            'title' => 'Batch Stock Valuation',
            'title_ar' => 'تقييم مخزون الدفعات',
            'permission' => 'reports',
            'filters' => ['branch_id'],
        ],
        'pos-daily-sales' => [
            'legacy' => 'POSDaily',
            'category' => 'sales',
            'title' => 'POS Daily Sales',
            'title_ar' => 'مبيعات نقاط البيع اليومية',
            'permission' => 'pos',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'asset-disposal-register' => [
            'legacy' => 'AssetDisposal',
            'category' => 'finance',
            'title' => 'Asset Disposal Register',
            'title_ar' => 'سجل التخلص من الأصول',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
        ],
        'transport-shipments-report' => [
            'legacy' => 'TR',
            'category' => 'transport',
            'title' => 'Transport Report',
            'title_ar' => 'تقرير النقل',
            'permission' => 'transport',
            'filters' => ['from', 'to', 'branch_id', 'driver_id'],
        ],
        'transport-driver-report' => [
            'legacy' => 'TrDriver',
            'category' => 'transport',
            'title' => 'Transport Driver Report',
            'title_ar' => 'تقرير سائق النقل',
            'permission' => 'transport',
            'filters' => ['from', 'to', 'driver_id'],
        ],
        'transport-cash-report' => [
            'legacy' => 'TPCash',
            'category' => 'transport',
            'title' => 'Transport Cash',
            'title_ar' => 'نقدية النقل',
            'permission' => 'transport',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'shipping-status-report' => [
            'legacy' => 'ShipSit',
            'category' => 'transport',
            'title' => 'Shipping Status',
            'title_ar' => 'حالة الشحن',
            'permission' => 'transport',
            'filters' => ['from', 'to', 'branch_id', 'status'],
        ],
        'attendance-time' => [
            'legacy' => 'TimeAtt',
            'category' => 'hr',
            'title' => 'Attendance Time',
            'title_ar' => 'تقرير الحضور',
            'permission' => 'hr',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'no-location-parts' => [
            'legacy' => 'NoLocation',
            'category' => 'inventory',
            'title' => 'Parts Without Location',
            'title_ar' => 'قطع بدون موقع',
            'permission' => 'reports',
            'filters' => ['branch_id', 'search'],
        ],
        'delivery-summary' => [
            'legacy' => 'DeliverySum',
            'category' => 'sales',
            'title' => 'Delivery Summary',
            'title_ar' => 'ملخص التسليم',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'labels-report' => [
            'legacy' => 'Labels',
            'category' => 'inventory',
            'title' => 'Part Labels',
            'title_ar' => 'ملصقات القطع',
            'permission' => 'parts',
            'filters' => ['search', 'branch_id'],
        ],
        'showroom-vehicle-sales' => [
            'legacy' => 'ShowRoomSales',
            'category' => 'sales',
            'title' => 'Showroom Vehicle Sales',
            'title_ar' => 'مبيعات معرض المركبات',
            'permission' => 'showroom-vehicles',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'showroom-transfer' => [
            'legacy' => 'SRTransfer',
            'category' => 'inventory',
            'title' => 'Showroom Transfer',
            'title_ar' => 'تحويلات المعرض',
            'permission' => 'showroom-vehicles',
            'filters' => ['from', 'to', 'branch_id'],
        ],
    ],

];
