<?php

return [
    'reports' => [
        'account-list-crystal' => [
            'legacy' => 'AccountList',
            'category' => 'finance',
            'title' => 'Account List Crystal',
            'title_ar' => 'Account List Crystal',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
            'handler' => 'gl-detail',
        ],
        'account-summary' => [
            'legacy' => 'AccSum',
            'category' => 'finance',
            'title' => 'Account Summary',
            'title_ar' => 'Account Summary',
            'permission' => 'finance',
            'filters' => ['as_of'],
            'handler' => 'trial-balance',
        ],
        'account-summary-detail' => [
            'legacy' => 'AccSum2',
            'category' => 'finance',
            'title' => 'Account Summary Detail',
            'title_ar' => 'Account Summary Detail',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
            'handler' => 'gl-detail',
        ],
        'aging-summary' => [
            'legacy' => 'Agingsum',
            'category' => 'finance',
            'title' => 'Aging Summary',
            'title_ar' => 'Aging Summary',
            'permission' => 'finance',
            'filters' => ['as_of'],
            'handler' => 'customer-aging',
        ],
        'cash-by-customer' => [
            'legacy' => 'CashCustomer',
            'category' => 'finance',
            'title' => 'Cash By Customer',
            'title_ar' => 'Cash By Customer',
            'permission' => 'finance',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'cash-transactions',
        ],
        'cash-register-alt' => [
            'legacy' => 'CashRep2',
            'category' => 'finance',
            'title' => 'Cash Register Alt',
            'title_ar' => 'Cash Register Alt',
            'permission' => 'finance',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'cash-book-register',
        ],
        'cheque-report' => [
            'legacy' => 'ChequeRpt',
            'category' => 'finance',
            'title' => 'Cheque Report',
            'title_ar' => 'Cheque Report',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
            'handler' => 'payment-receipts',
        ],
        'chart-accounts-iaapco' => [
            'legacy' => 'ChAcIaapco',
            'category' => 'masters',
            'title' => 'Chart Accounts Iaapco',
            'title_ar' => 'Chart Accounts Iaapco',
            'permission' => 'finance',
            'filters' => ['as_of'],
            'handler' => 'trial-balance',
        ],
        'customer-list-ar' => [
            'legacy' => 'CustomerArb',
            'category' => 'masters',
            'title' => 'Customer List Ar',
            'title_ar' => 'Customer List Ar',
            'permission' => 'reports',
            'filters' => [],
            'handler' => 'customer-list',
            'locale' => 'ar',
        ],
        'customer-report-alt2' => [
            'legacy' => 'CustRep2',
            'category' => 'sales',
            'title' => 'Customer Report Alt2',
            'title_ar' => 'Customer Report Alt2',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'sales-by-customer',
        ],
        'customer-report-summary' => [
            'legacy' => 'CustRep3',
            'category' => 'sales',
            'title' => 'Customer Report Summary',
            'title_ar' => 'Customer Report Summary',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'sales-by-customer',
        ],
        'customer-type-ar' => [
            'legacy' => 'CustTypeArb',
            'category' => 'masters',
            'title' => 'Customer Type Ar',
            'title_ar' => 'Customer Type Ar',
            'permission' => 'reports',
            'filters' => [],
            'handler' => 'customer-list',
            'locale' => 'ar',
        ],
        'customer-type-list' => [
            'legacy' => 'CustTypeList',
            'category' => 'masters',
            'title' => 'Customer Type List',
            'title_ar' => 'Customer Type List',
            'permission' => 'reports',
            'filters' => [],
            'handler' => 'customer-list',
        ],
        'qty-difference' => [
            'legacy' => 'DiffQtyRep',
            'category' => 'inventory',
            'title' => 'Qty Difference',
            'title_ar' => 'Qty Difference',
            'permission' => 'reports',
            'filters' => ['branch_id'],
            'handler' => 'physical-inventory',
        ],
        'discount-ar' => [
            'legacy' => 'DiscountArb',
            'category' => 'sales',
            'title' => 'Discount Ar',
            'title_ar' => 'Discount Ar',
            'permission' => 'reports',
            'filters' => ['from', 'to'],
            'handler' => 'sale-summary',
            'locale' => 'ar',
        ],
        'delivery-note-rpt' => [
            'legacy' => 'DNote',
            'category' => 'sales',
            'title' => 'Delivery Note Rpt',
            'title_ar' => 'Delivery Note Rpt',
            'permission' => 'reports',
            'filters' => ['from', 'to'],
            'handler' => 'daily-transactions',
        ],
        'delivery-note-alt' => [
            'legacy' => 'DNote2',
            'category' => 'sales',
            'title' => 'Delivery Note Alt',
            'title_ar' => 'Delivery Note Alt',
            'permission' => 'reports',
            'filters' => ['from', 'to'],
            'handler' => 'daily-transactions',
        ],
        'duplicate-locations' => [
            'legacy' => 'DoubLocs',
            'category' => 'inventory',
            'title' => 'Duplicate Locations',
            'title_ar' => 'Duplicate Locations',
            'permission' => 'reports',
            'filters' => ['branch_id'],
            'handler' => 'stock-by-location',
        ],
        'duplicate-parts' => [
            'legacy' => 'DoubParts',
            'category' => 'inventory',
            'title' => 'Duplicate Parts',
            'title_ar' => 'Duplicate Parts',
            'permission' => 'reports',
            'filters' => ['search'],
            'handler' => 'parts-master',
        ],
        'franchise-monthly' => [
            'legacy' => 'FrMon',
            'category' => 'sales',
            'title' => 'Franchise Monthly',
            'title_ar' => 'Franchise Monthly',
            'permission' => 'reports',
            'filters' => ['from', 'to'],
            'handler' => 'monthly-sales-branch',
        ],
        'ict-report' => [
            'legacy' => 'ICTReport',
            'category' => 'finance',
            'title' => 'Ict Report',
            'title_ar' => 'Ict Report',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
            'handler' => 'income-statement',
        ],
        'income-statement-alt1' => [
            'legacy' => 'Income1',
            'category' => 'finance',
            'title' => 'Income Statement Alt1',
            'title_ar' => 'Income Statement Alt1',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
            'handler' => 'income-statement',
        ],
        'income-statement-alt3' => [
            'legacy' => 'Income3',
            'category' => 'finance',
            'title' => 'Income Statement Alt3',
            'title_ar' => 'Income Statement Alt3',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
            'handler' => 'income-statement',
        ],
        'income-statement-stat' => [
            'legacy' => 'IncomeStat',
            'category' => 'finance',
            'title' => 'Income Statement Stat',
            'title_ar' => 'Income Statement Stat',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
            'handler' => 'income-statement',
        ],
        'istimara-status-rpt' => [
            'legacy' => 'IstimaraStatus',
            'category' => 'workshop',
            'title' => 'Istimara Status Rpt',
            'title_ar' => 'Istimara Status Rpt',
            'permission' => 'hr',
            'filters' => ['days'],
            'handler' => 'expiring-documents',
        ],
        'license-status-rpt' => [
            'legacy' => 'LicenseStatus',
            'category' => 'workshop',
            'title' => 'License Status Rpt',
            'title_ar' => 'License Status Rpt',
            'permission' => 'hr',
            'filters' => ['days'],
            'handler' => 'expiring-documents',
        ],
        'location-list' => [
            'legacy' => 'LocationList',
            'category' => 'masters',
            'title' => 'Location List',
            'title_ar' => 'Location List',
            'permission' => 'reports',
            'filters' => ['branch_id'],
            'handler' => 'stock-by-location',
        ],
        'log-file-report' => [
            'legacy' => 'LogFileRep',
            'category' => 'masters',
            'title' => 'Log File Report',
            'title_ar' => 'Log File Report',
            'permission' => 'audit-logs',
            'filters' => ['from', 'to'],
            'handler' => 'audit-log-report',
        ],
        'manufacturer-codes-ar' => [
            'legacy' => 'MfrCodeArb',
            'category' => 'masters',
            'title' => 'Manufacturer Codes Ar',
            'title_ar' => 'Manufacturer Codes Ar',
            'permission' => 'reports',
            'filters' => [],
            'handler' => 'manufacturer-codes',
            'locale' => 'ar',
        ],
        'monthly-transactions' => [
            'legacy' => 'MonthTrans',
            'category' => 'sales',
            'title' => 'Monthly Transactions',
            'title_ar' => 'Monthly Transactions',
            'permission' => 'reports',
            'filters' => ['from', 'to'],
            'handler' => 'monthly-sales-branch',
        ],
        'movement-report' => [
            'legacy' => 'MoveRep',
            'category' => 'inventory',
            'title' => 'Movement Report',
            'title_ar' => 'Movement Report',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'stock-movements',
        ],
        'new-stock-report' => [
            'legacy' => 'NewStkRep',
            'category' => 'inventory',
            'title' => 'New Stock Report',
            'title_ar' => 'New Stock Report',
            'permission' => 'reports',
            'filters' => ['branch_id'],
            'handler' => 'stock-listing',
        ],
        'other-services-rpt' => [
            'legacy' => 'OtherServices',
            'category' => 'workshop',
            'title' => 'Other Services Rpt',
            'title_ar' => 'Other Services Rpt',
            'permission' => 'workshop',
            'filters' => ['from', 'to'],
            'handler' => 'job-cards',
        ],
        'physical-invoice' => [
            'legacy' => 'PhInv',
            'category' => 'inventory',
            'title' => 'Physical Invoice',
            'title_ar' => 'Physical Invoice',
            'permission' => 'reports',
            'filters' => ['branch_id'],
            'handler' => 'physical-inventory',
        ],
        'physical-inventory-edit' => [
            'legacy' => 'PhyInvEdit',
            'category' => 'inventory',
            'title' => 'Physical Inventory Edit',
            'title_ar' => 'Physical Inventory Edit',
            'permission' => 'reports',
            'filters' => ['branch_id'],
            'handler' => 'physical-inventory',
        ],
        'purchase-order-rpt' => [
            'legacy' => 'PoRep',
            'category' => 'purchase',
            'title' => 'Purchase Order Rpt',
            'title_ar' => 'Purchase Order Rpt',
            'permission' => 'reports',
            'filters' => ['branch_id'],
            'handler' => 'pending-po',
        ],
        'purchase-report' => [
            'legacy' => 'PurcasheRpt',
            'category' => 'purchase',
            'title' => 'Purchase Report',
            'title_ar' => 'Purchase Report',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'purchase-summary',
        ],
        'purchases-by-month' => [
            'legacy' => 'PurchasebyMonths',
            'category' => 'purchase',
            'title' => 'Purchases By Month',
            'title_ar' => 'Purchases By Month',
            'permission' => 'reports',
            'filters' => ['from', 'to'],
            'handler' => 'purchase-summary',
        ],
        'pick-ticket-rpt' => [
            'legacy' => 'PickTicket',
            'category' => 'inventory',
            'title' => 'Pick Ticket Rpt',
            'title_ar' => 'Pick Ticket Rpt',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'pick-ticket-list',
        ],
        'pick-ticket-alt' => [
            'legacy' => 'PickTicket2',
            'category' => 'inventory',
            'title' => 'Pick Ticket Alt',
            'title_ar' => 'Pick Ticket Alt',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'pick-ticket-list',
        ],
        'sales-performa-rpt' => [
            'legacy' => 'SalesPerforma',
            'category' => 'sales',
            'title' => 'Sales Performa Rpt',
            'title_ar' => 'Sales Performa Rpt',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'proforma-list',
        ],
        'showroom-quotation' => [
            'legacy' => 'SQoutation',
            'category' => 'sales',
            'title' => 'Showroom Quotation',
            'title_ar' => 'Showroom Quotation',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'quotations',
        ],
        'showroom-report' => [
            'legacy' => 'ShowRoom',
            'category' => 'inventory',
            'title' => 'Showroom Report',
            'title_ar' => 'Showroom Report',
            'permission' => 'reports',
            'filters' => ['branch_id'],
            'handler' => 'showroom-stock',
        ],
        'showroom-summary-sr1' => [
            'legacy' => 'SR1',
            'category' => 'sales',
            'title' => 'Showroom Summary Sr1',
            'title_ar' => 'Showroom Summary Sr1',
            'permission' => 'reports',
            'filters' => ['from', 'to'],
            'handler' => 'branch-performance',
        ],
        'showroom-purchase-rpt' => [
            'legacy' => 'SRPurchaseReport',
            'category' => 'purchase',
            'title' => 'Showroom Purchase Rpt',
            'title_ar' => 'Showroom Purchase Rpt',
            'permission' => 'reports',
            'filters' => ['from', 'to'],
            'handler' => 'purchase-summary',
        ],
        'showroom-orders-rpt' => [
            'legacy' => 'SRreportOrder',
            'category' => 'workshop',
            'title' => 'Showroom Orders Rpt',
            'title_ar' => 'Showroom Orders Rpt',
            'permission' => 'workshop',
            'filters' => ['from', 'to'],
            'handler' => 'job-cards',
        ],
        'showroom-returns-rpt' => [
            'legacy' => 'SRtnSales1',
            'category' => 'sales',
            'title' => 'Showroom Returns Rpt',
            'title_ar' => 'Showroom Returns Rpt',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'sales-returns',
        ],
        'showroom-sales-rpt' => [
            'legacy' => 'SSales',
            'category' => 'sales',
            'title' => 'Showroom Sales Rpt',
            'title_ar' => 'Showroom Sales Rpt',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'sale-summary',
        ],
        'statement-account-ft' => [
            'legacy' => 'StateAccFT',
            'category' => 'finance',
            'title' => 'Statement Account Ft',
            'title_ar' => 'Statement Account Ft',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
            'handler' => 'customer-statement-report',
        ],
        'statement-account' => [
            'legacy' => 'StateAcct',
            'category' => 'finance',
            'title' => 'Statement Account',
            'title_ar' => 'Statement Account',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
            'handler' => 'customer-statement-report',
        ],
        'statement-account-alt' => [
            'legacy' => 'StateAcct3',
            'category' => 'finance',
            'title' => 'Statement Account Alt',
            'title_ar' => 'Statement Account Alt',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
            'handler' => 'vendor-statement-report',
        ],
        'stock-adjustment-rpt' => [
            'legacy' => 'StockAdj',
            'category' => 'inventory',
            'title' => 'Stock Adjustment Rpt',
            'title_ar' => 'Stock Adjustment Rpt',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'movement_type'],
            'handler' => 'stock-movements',
        ],
        'stock-order-rpt' => [
            'legacy' => 'StockOrd',
            'category' => 'inventory',
            'title' => 'Stock Order Rpt',
            'title_ar' => 'Stock Order Rpt',
            'permission' => 'reports',
            'filters' => ['branch_id'],
            'handler' => 'stock-listing',
        ],
        'stock-report-legacy' => [
            'legacy' => 'stockreport',
            'category' => 'inventory',
            'title' => 'Stock Report Legacy',
            'title_ar' => 'Stock Report Legacy',
            'permission' => 'reports',
            'filters' => ['branch_id'],
            'handler' => 'stock-listing',
        ],
        'stock-summary-legacy' => [
            'legacy' => 'stocksummary',
            'category' => 'inventory',
            'title' => 'Stock Summary Legacy',
            'title_ar' => 'Stock Summary Legacy',
            'permission' => 'reports',
            'filters' => ['branch_id'],
            'handler' => 'stock-valuation',
        ],
        'attendance-time' => [
            'legacy' => 'TimeAtt',
            'category' => 'hr',
            'title' => 'Attendance Time',
            'title_ar' => 'Attendance Time',
            'permission' => 'hr',
            'filters' => ['from', 'to'],
            'handler' => 'payroll-summary',
        ],
        'total-summary' => [
            'legacy' => 'TotalRep',
            'category' => 'sales',
            'title' => 'Total Summary',
            'title_ar' => 'Total Summary',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'sale-summary',
        ],
        'transport-cash' => [
            'legacy' => 'TPCash',
            'category' => 'finance',
            'title' => 'Transport Cash',
            'title_ar' => 'Transport Cash',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
            'handler' => 'cash-transactions',
        ],
        'transport-report' => [
            'legacy' => 'TR',
            'category' => 'workshop',
            'title' => 'Transport Report',
            'title_ar' => 'Transport Report',
            'permission' => 'workshop',
            'filters' => ['from', 'to'],
            'handler' => 'job-cards',
        ],
        'trial-balance-legacy' => [
            'legacy' => 'trailbalance',
            'category' => 'finance',
            'title' => 'Trial Balance Legacy',
            'title_ar' => 'Trial Balance Legacy',
            'permission' => 'finance',
            'filters' => ['as_of'],
            'handler' => 'trial-balance',
        ],
        'transfer-receive' => [
            'legacy' => 'TransferRecieve',
            'category' => 'inventory',
            'title' => 'Transfer Receive',
            'title_ar' => 'Transfer Receive',
            'permission' => 'reports',
            'filters' => ['from', 'to'],
            'handler' => 'stock-transfers-report',
        ],
        'transport-driver' => [
            'legacy' => 'TrDriver',
            'category' => 'workshop',
            'title' => 'Transport Driver',
            'title_ar' => 'Transport Driver',
            'permission' => 'workshop',
            'filters' => ['from', 'to'],
            'handler' => 'job-cards',
        ],
        'transport-driver-alt' => [
            'legacy' => 'TrDriver2',
            'category' => 'workshop',
            'title' => 'Transport Driver Alt',
            'title_ar' => 'Transport Driver Alt',
            'permission' => 'workshop',
            'filters' => ['from', 'to'],
            'handler' => 'job-cards',
        ],
        'units-list-ar' => [
            'legacy' => 'UnitArb',
            'category' => 'masters',
            'title' => 'Units List Ar',
            'title_ar' => 'Units List Ar',
            'permission' => 'reports',
            'filters' => [],
            'handler' => 'parts-master',
            'locale' => 'ar',
        ],
        'units-list' => [
            'legacy' => 'UnitList',
            'category' => 'masters',
            'title' => 'Units List',
            'title_ar' => 'Units List',
            'permission' => 'reports',
            'filters' => [],
            'handler' => 'parts-master',
        ],
        'variance-report' => [
            'legacy' => 'VarRep',
            'category' => 'inventory',
            'title' => 'Variance Report',
            'title_ar' => 'Variance Report',
            'permission' => 'reports',
            'filters' => ['branch_id'],
            'handler' => 'physical-inventory',
        ],
        'vehicle-expenses-rpt' => [
            'legacy' => 'VehExpense',
            'category' => 'workshop',
            'title' => 'Vehicle Expenses Rpt',
            'title_ar' => 'Vehicle Expenses Rpt',
            'permission' => 'workshop',
            'filters' => ['from', 'to'],
            'handler' => 'job-cards',
        ],
        'vehicle-orders-report' => [
            'legacy' => 'VehicleOrder',
            'category' => 'workshop',
            'title' => 'Vehicle Orders Report',
            'title_ar' => 'Vehicle Orders Report',
            'permission' => 'workshop',
            'filters' => ['from', 'to'],
            'handler' => 'job-cards',
        ],
        'wip-report-full' => [
            'legacy' => 'WIPReport',
            'category' => 'workshop',
            'title' => 'Wip Report Full',
            'title_ar' => 'Wip Report Full',
            'permission' => 'workshop',
            'filters' => ['branch_id'],
            'handler' => 'workshop-wip',
        ],
        'daily-cash-cr' => [
            'legacy' => 'cr-Cash',
            'category' => 'finance',
            'title' => 'Daily Cash Cr',
            'title_ar' => 'Daily Cash Cr',
            'permission' => 'finance',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'cash-book-register',
        ],
        'daily-trans-alt1' => [
            'legacy' => 'DailyTrans1',
            'category' => 'sales',
            'title' => 'Daily Trans Alt1',
            'title_ar' => 'Daily Trans Alt1',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'daily-transactions',
        ],
        'daily-trans-alt3' => [
            'legacy' => 'DailyTrans3',
            'category' => 'sales',
            'title' => 'Daily Trans Alt3',
            'title_ar' => 'Daily Trans Alt3',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'daily-transactions',
        ],
        'general-report-legacy' => [
            'legacy' => 'GenRptOld',
            'category' => 'finance',
            'title' => 'General Report Legacy',
            'title_ar' => 'General Report Legacy',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
            'handler' => 'journal-entries-report',
        ],
        'no-count-parts' => [
            'legacy' => 'nocount',
            'category' => 'inventory',
            'title' => 'No Count Parts',
            'title_ar' => 'No Count Parts',
            'permission' => 'reports',
            'filters' => ['days'],
            'handler' => 'parts-without-movement',
        ],
        'shipping-status' => [
            'legacy' => 'ShipSit',
            'category' => 'sales',
            'title' => 'Shipping Status',
            'title_ar' => 'Shipping Status',
            'permission' => 'reports',
            'filters' => ['from', 'to'],
            'handler' => 'daily-transactions',
        ],
        'return-sales-alt' => [
            'legacy' => 'RtnSales1',
            'category' => 'sales',
            'title' => 'Return Sales Alt',
            'title_ar' => 'Return Sales Alt',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'sales-returns',
        ],
        'return-sales-total' => [
            'legacy' => 'RtSaleT',
            'category' => 'sales',
            'title' => 'Return Sales Total',
            'title_ar' => 'Return Sales Total',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
            'handler' => 'sales-returns',
        ],
        'workshop-stock-legacy' => [
            'legacy' => 'workshopstock',
            'category' => 'inventory',
            'title' => 'Workshop Stock Legacy',
            'title_ar' => 'Workshop Stock Legacy',
            'permission' => 'reports',
            'filters' => ['branch_id'],
            'handler' => 'workshop-stock',
        ],
        'showroom-vehicle-stock' => [
            'legacy' => 'SRstock',
            'category' => 'inventory',
            'title' => 'Showroom Vehicle Stock',
            'title_ar' => 'Showroom Vehicle Stock',
            'permission' => 'showroom-vehicles',
            'filters' => ['branch_id'],
            'native' => true,
        ],
        'showroom-vehicle-sales-rpt' => [
            'legacy' => 'ShowRoomSales',
            'category' => 'sales',
            'title' => 'Showroom Vehicle Sales Rpt',
            'title_ar' => 'Showroom Vehicle Sales Rpt',
            'permission' => 'showroom-vehicles',
            'filters' => ['from', 'to', 'branch_id'],
            'native' => true,
        ],
        'chassis-tracker' => [
            'legacy' => 'ChassisTrack',
            'category' => 'inventory',
            'title' => 'Chassis Tracker',
            'title_ar' => 'Chassis Tracker',
            'permission' => 'showroom-vehicles',
            'filters' => ['search', 'branch_id'],
            'native' => true,
        ],
        'showroom-transfer-rpt' => [
            'legacy' => 'SRTransfer',
            'category' => 'inventory',
            'title' => 'Showroom Transfer Rpt',
            'title_ar' => 'Showroom Transfer Rpt',
            'permission' => 'showroom-vehicles',
            'filters' => ['from', 'to', 'branch_id'],
            'native' => true,
        ],
    ],
];
