<?php

return [

    'categories' => [
        'sales' => ['label' => 'Sales', 'label_ar' => 'المبيعات'],
        'inventory' => ['label' => 'Inventory', 'label_ar' => 'المخزون'],
        'purchase' => ['label' => 'Purchase', 'label_ar' => 'المشتريات'],
        'finance' => ['label' => 'Finance', 'label_ar' => 'المالية'],
        'workshop' => ['label' => 'Workshop', 'label_ar' => 'الورشة'],
        'hr' => ['label' => 'HR', 'label_ar' => 'الموارد البشرية'],
        'masters' => ['label' => 'Master Lists', 'label_ar' => 'القوائم الرئيسية'],
    ],

    'reports' => [
        'customer-list' => [
            'legacy' => 'CustomerList',
            'category' => 'masters',
            'title' => 'Customer List',
            'title_ar' => 'قائمة العملاء',
            'permission' => 'reports',
            'filters' => [],
        ],
        'vendor-list' => [
            'legacy' => 'VendorList',
            'category' => 'masters',
            'title' => 'Vendor List',
            'title_ar' => 'قائمة الموردين',
            'permission' => 'reports',
            'filters' => [],
        ],
        'parts-master' => [
            'legacy' => 'PartNoArb',
            'category' => 'masters',
            'title' => 'Parts Master List',
            'title_ar' => 'قائمة قطع الغيار',
            'permission' => 'reports',
            'filters' => ['search'],
        ],
        'sale-summary' => [
            'legacy' => 'SaleSummary',
            'category' => 'sales',
            'title' => 'Sales Summary',
            'title_ar' => 'ملخص المبيعات',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'sales-by-customer' => [
            'legacy' => 'CustRep',
            'category' => 'sales',
            'title' => 'Sales by Customer',
            'title_ar' => 'المبيعات حسب العميل',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'monthly-sales-branch' => [
            'legacy' => 'MonSalBrn',
            'category' => 'sales',
            'title' => 'Monthly Sales by Branch',
            'title_ar' => 'المبيعات الشهرية حسب الفرع',
            'permission' => 'reports',
            'filters' => ['from', 'to'],
        ],
        'daily-transactions' => [
            'legacy' => 'DailyTrans',
            'category' => 'sales',
            'title' => 'Daily Transactions',
            'title_ar' => 'المعاملات اليومية',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'sales-returns' => [
            'legacy' => 'RtnSales',
            'category' => 'sales',
            'title' => 'Sales Returns',
            'title_ar' => 'مرتجعات المبيعات',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'quotations' => [
            'legacy' => 'Qoutation',
            'category' => 'sales',
            'title' => 'Quotations List',
            'title_ar' => 'قائمة عروض الأسعار',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'top-selling-parts' => [
            'legacy' => 'SaleSummary',
            'category' => 'sales',
            'title' => 'Top Selling Parts',
            'title_ar' => 'أكثر القطع مبيعاً',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'stock-listing' => [
            'legacy' => 'Stock',
            'category' => 'inventory',
            'title' => 'Stock Listing',
            'title_ar' => 'قائمة المخزون',
            'permission' => 'reports',
            'filters' => ['branch_id', 'search'],
        ],
        'stock-by-branch' => [
            'legacy' => 'BrhQty',
            'category' => 'inventory',
            'title' => 'Stock by Branch',
            'title_ar' => 'المخزون حسب الفرع',
            'permission' => 'reports',
            'filters' => ['search'],
        ],
        'stock-by-location' => [
            'legacy' => 'LocRep',
            'category' => 'inventory',
            'title' => 'Stock by Location',
            'title_ar' => 'المخزون حسب الموقع',
            'permission' => 'reports',
            'filters' => ['branch_id', 'search'],
        ],
        'stock-cardex' => [
            'legacy' => 'Cardex',
            'category' => 'inventory',
            'title' => 'Stock Cardex',
            'title_ar' => 'كاردكس المخزون',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'part_id', 'branch_id'],
        ],
        'stock-movements' => [
            'legacy' => 'DailyTrans2',
            'category' => 'inventory',
            'title' => 'Stock Movements',
            'title_ar' => 'حركات المخزون',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id', 'movement_type'],
        ],
        'low-stock' => [
            'legacy' => 'StockOrder',
            'category' => 'inventory',
            'title' => 'Low Stock Alert',
            'title_ar' => 'تنبيه المخزون المنخفض',
            'permission' => 'reports',
            'filters' => ['branch_id'],
        ],
        'dead-stock' => [
            'legacy' => 'DeadStock',
            'category' => 'inventory',
            'title' => 'Dead Stock',
            'title_ar' => 'مخزون راكد',
            'permission' => 'reports',
            'filters' => ['branch_id', 'days'],
        ],
        'purchase-summary' => [
            'legacy' => 'InvReport',
            'category' => 'purchase',
            'title' => 'Purchase Summary',
            'title_ar' => 'ملخص المشتريات',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'daily-purchases' => [
            'legacy' => 'DailyPurTrans',
            'category' => 'purchase',
            'title' => 'Daily Purchase Transactions',
            'title_ar' => 'مشتريات يومية',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'purchases-by-vendor' => [
            'legacy' => 'ForiegnPur',
            'category' => 'purchase',
            'title' => 'Purchases by Vendor',
            'title_ar' => 'المشتريات حسب المورد',
            'permission' => 'reports',
            'filters' => ['from', 'to', 'branch_id'],
        ],
        'pending-po' => [
            'legacy' => 'PendingPO',
            'category' => 'purchase',
            'title' => 'Pending Purchase Orders',
            'title_ar' => 'أوامر شراء معلقة',
            'permission' => 'reports',
            'filters' => ['branch_id'],
        ],
        'trial-balance' => [
            'legacy' => 'GLSumRep',
            'category' => 'finance',
            'title' => 'Trial Balance',
            'title_ar' => 'ميزان المراجعة',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
            'view' => 'trial_balance',
        ],
        'income-statement' => [
            'legacy' => 'Income',
            'category' => 'finance',
            'title' => 'Income Statement',
            'title_ar' => 'قائمة الدخل',
            'permission' => 'finance',
            'filters' => ['from', 'to'],
            'view' => 'income_statement',
        ],
        'balance-sheet' => [
            'legacy' => 'BALANCESHEET',
            'category' => 'finance',
            'title' => 'Balance Sheet',
            'title_ar' => 'الميزانية العمومية',
            'permission' => 'finance',
            'filters' => ['as_of'],
            'view' => 'balance_sheet',
        ],
        'customer-aging' => [
            'legacy' => 'AgingList',
            'category' => 'finance',
            'title' => 'Customer Aging',
            'title_ar' => 'أعمار ديون العملاء',
            'permission' => 'finance',
            'filters' => [],
            'view' => 'aging',
        ],
        'vendor-aging' => [
            'legacy' => 'AgeRep',
            'category' => 'finance',
            'title' => 'Vendor Aging',
            'title_ar' => 'أعمار ديون الموردين',
            'permission' => 'finance',
            'filters' => [],
            'view' => 'aging',
        ],
        'job-cards' => [
            'legacy' => 'JobCard',
            'category' => 'workshop',
            'title' => 'Job Cards',
            'title_ar' => 'بطاقات العمل',
            'permission' => 'workshop',
            'filters' => ['from', 'to', 'branch_id', 'status'],
        ],
        'workshop-wip' => [
            'legacy' => 'WIP',
            'category' => 'workshop',
            'title' => 'Work In Progress',
            'title_ar' => 'أعمال قيد التنفيذ',
            'permission' => 'workshop',
            'filters' => ['branch_id'],
        ],
        'payroll-summary' => [
            'legacy' => 'Payroll',
            'category' => 'hr',
            'title' => 'Payroll Summary',
            'title_ar' => 'ملخص الرواتب',
            'permission' => 'hr',
            'filters' => ['from', 'to'],
        ],
        'expiring-documents' => [
            'legacy' => 'AqamaStatus',
            'category' => 'hr',
            'title' => 'Expiring Documents',
            'title_ar' => 'وثائق منتهية الصلاحية',
            'permission' => 'hr',
            'filters' => ['days'],
            'view' => 'expiring',
        ],
    ],

];
